logging:
  level:
    com.example.pamiwpostapp.backend: DEBUG

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect